left-shoulder:      -0.037
left-elbow:         0.035
left-wrist:         2.36
left-z:             -263.89

right-shoulder:     0.0685
right-elbow:        -0.055
right-wrist:        2.36
right-z:            -263.89

left-shoulder-dir:  -1
left-elbow-dir:     -1
left-wrist-dir:     1
left-z-dir:         1

right-shoulder-dir: -1
right-elbow-dir:    -1
right-wrist-dir:    1
right-z-dir:        1
