
actuator:
    left-z:
        stream:
            current_pid: 0
            velocity_pid: 0
            position_pid: 0
            motor_pos: 0
            index: 0
        motor:
            # motor: 1516SR
            mode: 3 # bounded
            motor_encoder_steps_per_revolution: 4096
            # transmission: motor: 1/1 gears: 16/42
            transmission_ratio_p: 8
            transmission_ratio_q: 21
            torque_constant: 0.016 # Nm/A
        control:
            current:
                kp: 3.
                ki: 500.
                kd: 0.
                ilimit: 100.

            velocity:
                kp: 0.005
                ki: 0.05
                kd: 0.
                ilimit: 0.2
            position:
                kp: 0.1
                ki: 0.01
                kd: 0.

            low_batt_th: 12
            acceleration_limit: 2500.
            velocity_limit: 2000.
            torque_limit: 1.3
