actuator:
    left-shoulder:
        stream:
            current_pid: 0
            velocity_pid: 0
            position_pid: 0
            motor_pos: 0
            index: 0
        motor:
            # motor: 1516SR
            mode: 3 # bounded
            motor_encoder_steps_per_revolution: 2048
            # transmission: motor: 1/76 gears: 20/80
            transmission_ratio_p: 1
            transmission_ratio_q: 304
            torque_constant: 0.00826 # Nm/A
        control:
            current:
                kp: 24.
                ki: 5000.
                kd: 0.
                ilimit: 100.

            velocity:
                kp: 0.2
                ki: 0.8
                kd: 0.
                ilimit: 0.13
            position:
                kp: 6
                ki: 1.
                kd: 2.

            low_batt_th: 12
            acceleration_limit: 10.
            velocity_limit: 2.
            torque_limit: 1

    left-elbow:
        stream:
            current_pid: 0
            velocity_pid: 0
            position_pid: 0
            motor_pos: 0
            index: 0
        motor:
            # motor: 1516SR
            mode: 3 # bounded
            motor_encoder_steps_per_revolution: 2048
            # transmission: motor: 1/76 gears: 20/60
            transmission_ratio_p: 1
            transmission_ratio_q: 228
            torque_constant: 0.00826 # Nm/A
        control:
            current:
                kp: 24.
                ki: 5000.
                kd: 0.
                ilimit: 100.

            velocity:
                kp: 8
                ki: 1
                kd: 0.
                ilimit: 0.5
            position:
                kp: 12
                ki: 0.
                kd: 0.

            low_batt_th: 12
            acceleration_limit: 20.
            velocity_limit: 5.
            torque_limit: 3

    left-z:
        stream:
            current_pid: 0
            velocity_pid: 0
            position_pid: 0
            motor_pos: 0
            index: 0
        motor:
            # motor: 1516SR
            mode: 3 # bounded
            motor_encoder_steps_per_revolution: 4096
            # transmission: motor: 1/1 gears: 16/42
            transmission_ratio_p: 8
            transmission_ratio_q: 21
            torque_constant: 0.016 # Nm/A
        control:
            current:
                kp: 3.
                ki: 500.
                kd: 0.
                ilimit: 100.

            velocity:
                kp: 0.005
                ki: 0.05
                kd: 0.
                ilimit: 0.2
            position:
                kp: 0.1
                ki: 0.01
                kd: 0.

            low_batt_th: 12
            acceleration_limit: 2500.
            velocity_limit: 2000.
            torque_limit: 1.3

    left-wrist:
        stream:
            current_pid: 0
            velocity_pid: 0
            position_pid: 0
            motor_pos: 0
            index: 0
        motor:
            # motor: 1516SR
            mode: 2 # periodic
            motor_encoder_steps_per_revolution: 4096
            # transmission: motor: 1/76 gears: 20/50
            transmission_ratio_p: 1
            transmission_ratio_q: 190
            torque_constant: 0.0115 # Nm/A
        control:
            current:
                kp: 30.
                ki: 5000.
                kd: 0.
                ilimit: 100.

            velocity:
                kp: 0.5
                ki: 0.8
                kd: 0.
                ilimit: 0.13
            position:
                kp: 6
                ki: 1.
                kd: 2.

            low_batt_th: 12
            acceleration_limit: 100.
            velocity_limit: 3.
            torque_limit: 1.3
