master:
    odometry:
        wheelbase: 0.194
        radius_left: -0.016
        radius_right: 0.016

    tracy:
        damping: 0.7
        g: 60.

    waypoint_ctrl:
        heading:
            kp: 20.
            ki: 0.
            kd: 0.0
            ilimit: 50.
        distance:
            kp: 100.
            ki: 0.
            kd: 0.
            ilimit: 50.

actuator:
    left-wheel:
        stream:
            # Encoder position is needed for odometry
            encoder_pos: 100
            velocity_pid: 0
            position_pid: 0
        motor:
            mode: 2
            motor_encoder_steps_per_revolution: 4096
            second_encoder_steps_per_revolution: 16384
            transmission_ratio_p: 49
            transmission_ratio_q: 676
            torque_constant: 1.
        control:
            current:
                kp: 4.
                ki: 1500.
                kd: 0.
                ilimit: 50.

            velocity:
                kp: 14.
                ki: 110.
                kd: 0.
                ilimit: 1400.
            position:
                kp: 0.1
                ki: 0.5
                kd: 0.

            low_batt_th: 5.
            acceleration_limit: 100.
            velocity_limit: 50.
            torque_limit: 14.

    right-wheel:
       stream:
           # Encoder position is needed for odometry
           encoder_pos: 100
           position_pid: 0

       motor:
           mode: 2
           motor_encoder_steps_per_revolution: 4096
           second_encoder_steps_per_revolution: 16384
           transmission_ratio_p: 49
           transmission_ratio_q: 676
           torque_constant: 1.
       control:
            current:
               kp: 4.
               ki: 1500.
               kd: 0.
               ilimit: 50.
            velocity:
                kp: 14.
                ki: 110.
                kd: 0.
                ilimit: 1400.
            position:
                kp: 0.1
                ki: 0.5
                kd: 0.

            low_batt_th: 5.
            acceleration_limit: 100.
            velocity_limit: 50.
            torque_limit: 14.
