actuator:
    left-shoulder:
        stream:
            current_pid: 0
            velocity_pid: 0
            position_pid: 0
            motor_pos: 0
            index: 0
        motor:
            # motor: 1516SR
            mode: 3 # bounded
            motor_encoder_steps_per_revolution: 2048
            # transmission: motor: 1/76 gears: 20/80
            transmission_ratio_p: 1
            transmission_ratio_q: 304
            torque_constant: 0.00826 # Nm/A
        control:
            current:
                kp: 24.
                ki: 5000.
                kd: 0.
                ilimit: 100.

            velocity:
                kp: 0.2
                ki: 0.8
                kd: 0.
                ilimit: 0.13
            position:
                kp: 6
                ki: 1.
                kd: 2.

            low_batt_th: 12
            acceleration_limit: 100.
            velocity_limit: 1.
            torque_limit: 1

    left-elbow:
        stream:
            current_pid: 0
            velocity_pid: 0
            position_pid: 0
            motor_pos: 0
            index: 0
        motor:
            # motor: 1516SR
            mode: 3 # bounded
            motor_encoder_steps_per_revolution: 2048
            # transmission: motor: 1/76 gears: 20/60
            transmission_ratio_p: 1
            transmission_ratio_q: 228
            torque_constant: 0.00826 # Nm/A
        control:
            current:
                kp: 24.
                ki: 5000.
                kd: 0.
                ilimit: 100.

            velocity:
                kp: 0.2
                ki: 0.8
                kd: 0.
                ilimit: 0.13
            position:
                kp: 6
                ki: 1.
                kd: 2.

            low_batt_th: 12
            acceleration_limit: 100.
            velocity_limit: 1.
            torque_limit: 1
